### ISSUE TITLE
Database::getInsertId fails after inserts into tables without related sequences

### ISSUE THREAD

**Issue by pegro** [jjeising/framework#4]
Most tables have id columns based on a sequence, created using types like BIGSERIAL.
When new rows are inserted, for the id column the SQL function CURVAL() is called with the related sequence.

To retrieve the id of the newly created row, the SQL function LASTVAL() is available. In PHP this function is wrapped in the PDO function lastInsertId().

But: if the table the row is being inserted into has no id column, CURVAL() is never called and the call to LASTVAL() fails with "ERROR:  lastval is not yet defined in this session STATEMENT:  SELECT LASTVAL();"

Note: PDO::lastInsertId() doesn't fail and returns 0 with PHP < 7.0.10 or with newer PHP and Postgresql < 8.1. See https://github.com/php/php-src/commit/12628e9a46b91a0aa92fd0619cdd545c409d25a6

This is a problem with Database::execute(), which calls getInsertId() (which calls lastInsertId()) for all INSERT queries unconditionally. Database::executeReturning() should be fine.

**Comment by jjeising** [comment]
Thanks, the change in behaviour explains this why this issue came up and wasn't always reproducible.
